### PR TITLE
Updates to better integrate with development cycle

### PR DESCRIPTION
**Pull request by johnrengelman**
We use Fitnesse extensively for integration testing our application, so I made some improvements to the plugin to assist with our Continuous Integration.
1) Moved Fitnesse tests into it's own Phase/Type (fitnesse:fitnesse). I followed the Geb plugin's methodology to do this. This allows better control for when fitnesse tests are run. The phase runs in the integration mode
2) Modified the GrailsFitnesseTestRunner to correctly startup a Fitnesse server during the fitnesse test phase to execute fitnesse tests against. No need to have an external server or start 2 instances. 'grails test-app' will now run fitnesse tests as part of the test suite.
3) Output the Fitnesse XML test results to target/test-reports/fitnesse
4) Parse the Fitnesse XML test results and create generic JUnit Test objects. This allows the JUnit Reporting framework to output the .txt file and the JUnit .xml file. This also allows Fitnesse test results to participate in the Grails Test Report HTML file
5) Updated to latest fitnesse.jar. I tried to make this a BuildConfig dependency but this breaks compatibility with older versions of Grails (1.3.x) because the plugin and the jar file have the same name
6) Updated plugin project to Grails 2.0.1

One of the biggest reasons that I did this was so code coverage tools like Cobertura could generate coverage reports from the fitnesse tests. These updates allow that to happen.

I haven't updated the application.properties version to reflect any changes.

### CODE REVIEW

**Comment by bodiam** [comment]
Hi John,

Wow, that's quite some work! Thanks for that. I will merge it and create a new release asap! I hope I have some time to arrange this in the weekend! Great work, thanks again!

Erik

**Comment by johnrengelman** [comment]
Not a problem!
When I find some more time, I might dig into getting more of the results parsed out of the fitnesse files and added to mock JUnit Results objects.

**Comment by bodiam** [comment]
Hi John,

Anything you known which still needs to be parsed/added to the junit results? If I'm gonna merge, I might just as well take a look at it....

Erik

**Comment by johnrengelman** [comment]
Well, we are getting everything from the xml returned by the SlimService now into FitnesseTotalResult and FitnesseTestResult, but I was thinking of using pageHistoryLink value in FitnesseTotalResult (which points actual xml result for each test case on the disk) to generate more detailed test results.

For example, getting the actual assertion that failed or a more detailed exception stack trace. Right now, I'm just generating exceptions that say "Fitnesse reported an error" and you'd have to go search what the actual error is. It would be nice to have that right in the html that's generated from the test run. I just haven't looked at how those files are structured yet and what data I can get out of them.

So right now, we are parsing the response from the server: http://fitnesse.org/FitNesse.UserGuide.RestfulServices.RestfulSuiteXmlFormat

But I would like to parse the results file itself: http://fitnesse.org/FitNesse.UserGuide.RestfulTests

**Comment by johnrengelman** [comment]
Hey Erik,
Any progress on merging this in this weekend?

John

**Comment by johnrengelman** [comment]
Hey Erik,
Haven't heard back from you on this in a while. I was hoping to get these changes pulled into plugin and release an update so we can use it on the project I'm working on. I've also been thinking more about the changes I spoke of above. The Jenkins Fitnesse plugin recently released an update that does some HTML file parsing to get more test results and I might try to use their method within this plugin. I also have some changes in mind for the GrailsFitnesseSlimServer binding to 11 ports, since this causes issues when trying to run on a CI system with concurrent builds.

Anyway, I was hoping I could get some feedback from you. I release you are busy and if that's the case, I willing to handle plugin updates and releases if you want to off-load that. Let me know!

John

**Comment by bodiam** [comment]
hi John,

Sorry for taking such a long time. I have released the plugin, and I'll update the documentation later. I'm still going through all your changes at the moment. Wrong sequence, I know, but I trust your work after seeing some refactorings you put through.

Erik

**Comment by bodiam** [comment]
Hi John,

I'm testing the plugin a little bit by running the internal fitnesse for the amasun suite, but when I do, there are no fitnesse pages anymore. 
(go to test/projects/amasun, run grails run-fitnesse, browse to localhost:9090, and there's a amasun link, but no pages.) Did you test this? Else I'll try to fix it, but if you already had a look at it, it would be easier ;-)

Thanks,

Erik

**Comment by johnrengelman** [comment]
Hmm,
I took a look Erik and this is what I found.
All the sub-pages under FrontPage.AmasunSuite are commented out (take a look at test/projects/amasun/wiki/FitNesseRoot/FrontPage/AmasunSuite/content.txt, everything has a # next to it)

I looked at the history and it appears the only change that I made was to comment out the line for BuyBooksComboAmountTest. I remember doing that because it didn't have a corresponding directory in the project (i.e. it was a broken link which caused the tests to fail).

Not sure how you want to fix this.

Thanks,
John

**Comment by bodiam** [comment]
Hi John,

Thanks for the quick reply. You're right, I see it. I uncommented 
everything, and it works.

Small question though: when I run 'grails test-app fitnesse:fitnesse' 
in the test projects (after fixing Book), the tests all pass, but when 
I open the target/test-reports/html/index.html, the report says: No 
tests executed.

Did this work for you?

Erik

Citeren John Engelman 
reply@reply.github.com:

**Comment by johnrengelman** [comment]
Erik -
I did my testing with my own project apparently :(
I think what you are missing is a fitnesse directory under /test
Grails won't run a test phase if there isn't a matching directory. Adding this folder and a placeholder file should be part of the Install.groovy and Upgrade.groovy scripts for the plugin. 

John

**Comment by bodiam** [comment]
Hi John,

You're right! Creating the Fitnesse folder did the trick! Very weird, never heard of that! Where did you learn that?

I'll fix it in the Install and Upgrade script. I've got the 2.0.1 release ready, which includes all your changes, plus I spend the whole day on making it better (updating the documentation, fixing some user feedback, improved error handling, refactored some code, etc)

I'll update and release, probably this weekend, and send an announcement to the list. Thanks again for the help. Btw, if you want credentials to also publish the plugin, I wouldn't object to that, so that delays as before would no longer happen. I'm not sure how to arrange that, but I'm open to that.

Erik

**Comment by johnrengelman** [comment]
Erik -
I just got a chance to look back and I see what I did. I had the fitnesse directory created in my local copy, but because I didn't have a file inside the folder, it didn't get created in the git repo. So, I think the install and upgrade scripts should make a .donotdelete file, so that it forces whatever version control to actually create the directory.

As for having that directory, i think I ran into that same problem as I was trying to create the fitnesse phase and ended up having to look at the _GrailsTest.groovy script to figure out what was happening. I couldn't find a way to fake out the test system to run the phase even though the folder didn't exist.

As for credentials, I think it's ok for now. With this release, I'm not in such a hurry to get an update for any pull requests I make. Plus, I don't want to be releasing from different repos. If we get to that point, then I would need to be added to this repo and we can mail the grails-dev list to get my account added on grails.org for permissions on this plugin. Though, I don't think we are there just yet. Just thought I would offer to you to help lighten the load. 

I look forward to the 2.0.1 release and integrating into our project.

Thanks a bunch!!

John

**Pull request merged**
